apiVersion: v1
kind: Secret
metadata:
  name: nginx-scret
  namespace: test
type: Opaque
data:
  USER_NAME: cm9vdA==
  PASSWORD: MTIzNHBhc3N3b3Jk
  nginx_color.properties: |
    ICAgIGJsYWNrPSMwMDAwMDAKICAgIHdoaXRlPSNmZmZmZmY=